description: misc

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: whole_faiss
  sku: C40
  sku_count: 1
  command:
  - ./whole_faiss.sh whole_faiss
    /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_whole_avg_cell/repr.npz
    /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_whole_avg_cell/repr.npz.ret_top10_norm

- name: span_faiss_as_whole_faiss
  sku: C40
  sku_count: 1
  command:
  - ./whole_faiss.sh span_as_whole_faiss
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz.as_whole.ret_top10
- name: span_as_whole_faiss_sparsity
  sku: C40
  sku_count: 1
  command:
  - ./whole_faiss.sh span_as_whole_faiss
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz.as_whole.ret_top10.bak

- name: span_as_whole_faiss_original_tabert
  sku: C40
  sku_count: 1
  command:
  - ./whole_faiss.sh span_as_whole_faiss
    /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_span/repr.npz
    /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_span/repr.npz.as_whole.ret_top10

- name: gen_data
  sku: C40
  sku_count: 1
  command:
  - ./gen_maskdata.sh

- name: ner
  sku: C40
  sku_count: 1
  command:
  - ./ner.sh
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention.jsonl
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention.jsonl.ner

- name: ret_filter_by_faiss
  sku: C40
  sku_count: 1
  command:
  - ./ret_filter_by_faiss.sh
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention_dense_span_context_as_whole_maxsum.jsonl.data0
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz
    /mnt/root/TaBERT/data/runs/ret_wholetable_3merge_bert_mc_othertable/index/tapas_data0_span_context_optimized/repr.npz.as_whole.ret_top10
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention.jsonl.data0

- name: dummy_test
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_bart_mlm_contextmention
    data/runs/test seq2seq 24 5 null
