description: match

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: tapas_retbycontext
  sku: C40
  sku_count: 1
  command:
  - ./match.sh
    /mnt/root/tapas/data/pretrain/train/preprocessed.jsonl.tapas_ret10
    /mnt/root/tapas/data/pretrain/train/preprocessed.jsonl
    /mnt/root/tapas/data/pretrain/train/preprocessed.jsonl
    /mnt/root/tapas/data/pretrain/train/preprocessed_retbycontext_removeself.jsonl
    500000
- name: tapas_data0_dense_whole_avg_cell
  sku: C40
  sku_count: 1
  command:
  - ./match.sh
    /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_whole_avg_cell/repr.npz.ret_top10
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention.jsonl.data0.ner
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention.jsonl.data0.ner
    /mnt/root/tapas/data/pretrain/train/preprocessed_mention_dense_whole_avg_cell.jsonl.data0
    500000
