description: generate dense index

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: tapas_data0_whole_avg_cell
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_bert_mlm_data0
    /mnt/root/TaBERT/data/runs/tabert_base_k1 split_mlm 32 1
    '"/mnt/root/TaBERT/data/runs/tabert_base_k1/model.bin"'
    --only_test --mode represent-train --index_repr whole_avg_cell
    --output_file /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_whole_avg_cell
- name: tapas_data0_span
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_bert_mlm_data0
    /mnt/root/TaBERT/data/runs/tabert_base_k1 split_mlm 32 1
    '"/mnt/root/TaBERT/data/runs/tabert_base_k1/model.bin"'
    --only_test --mode represent-train --index_repr span_context
    --output_file /mnt/root/TaBERT/data/runs/tabert_base_k1/index/tapas_data0_span
