description: pretrain with setup in paper

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: wholetable_3merge_bart_bartmask_salientmask
  sku: G8
  sku_count: 9
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 48
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask seq2seq 8 10 null
- name: wholetable_3merge_bart_bartmask_salientmask_wtq_qa_allrow_1024
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_1024
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_wtq_qa_allrow_1024 seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask/pytorch_model_epoch09.bin"'
    --gradient-accumulation-steps 2 --mode generate-test --output_file ep9.tsv
- name: wholetable_3merge_bart_bartmask_salientmask_wtq_qa_allrow_1024_ep50
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 16
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_1024
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_wtq_qa_allrow_1024_ep50 seq2seq 6 50
    '"/mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask/pytorch_model_epoch09.bin"'
    --mode generate-test --output_file ep49.tsv

- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_bartlarge
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_bartlarge seq2seq 2 10 null
    --gradient-accumulation-steps 12 --base-model-name facebook/bart-large
- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_bartlarge_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa large full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_bartlarge/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexinit
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexinit seq2seq 2 10
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --gradient-accumulation-steps 12 --base-model-name facebook/bart-large
- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexinit_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa large
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexinit/pytorch_model_epoch09.bin 10:20:30

- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexbaseinit seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_bartmask_salientmask_tapexlinear_tapexbaseinit/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_tapex_bart_tapexbaseinit
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/tapex_bart
    /mnt/root/TaBERT/data/runs/wholetable_tapex_bart_tapexbaseinit seq2seq 6 1
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 12 --base-model-name facebook/bart-base
- name: wholetable_tapex_bart_tapexbaseinit_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapex_bart_tapexbaseinit/pytorch_model_epoch00.bin 10:30:50

- name: wholetable_3merge_tapex2shard_bart_bartmask_salientmask_tapexlinear_tapexbaseinit
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear-tapex_bart-20-2
    /mnt/root/TaBERT/data/runs/wholetable_3merge_tapex2shard_bart_bartmask_salientmask_tapexlinear_tapexbaseinit seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 4 --base-model-name facebook/bart-base
- name: wholetable_3merge_tapex2shard_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_tapex2shard_bart_bartmask_salientmask_tapexlinear_tapexbaseinit/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_dense_span_context_as_whole_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit seq2seq 8 10
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 9 --base-model-name facebook/bart-base
- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_continue
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_bartmask_salientmask_tapexlinear
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_continue seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit/pytorch_model_epoch09.bin"'
    --gradient-accumulation-steps 4 --base-model-name facebook/bart-base
- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit/pytorch_model_epoch09.bin 10:30:50
- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_continue_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_tapexbaseinit_continue/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_tapas_bart_retbycontext_bartmask_salientmask_tapexlinear_tapexbaseinit
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_bart_retbycontext_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_bart_retbycontext_bartmask_salientmask_tapexlinear_tapexbaseinit seq2seq 6 5
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 4 --base-model-name facebook/bart-base
- name: wholetable_tapas_bart_retbycontext_bartmask_salientmask_tapexlinear_tapexbaseinit_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_bart_retbycontext_bartmask_salientmask_tapexlinear_tapexbaseinit/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_dense_span_context_as_whole_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear seq2seq 8 10 null
    --gradient-accumulation-steps 9 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear/pytorch_model_epoch09.bin 10:30:50

- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_original_tabert
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_dense_span_context_as_whole_bartmask_salientmask_original_tabert
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_original_tabert seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_original_tabert_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_bartmask_salientmask_tapexlinear_original_tabert/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapas_data0_bart_retbycontext_bartmask_salientmask_tapexlinear
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_retbycontext_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_retbycontext_bartmask_salientmask_tapexlinear seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapas_data0_bart_retbycontext_bartmask_salientmask_tapexlinear_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_retbycontext_bartmask_salientmask_tapexlinear/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapas_data0_bart_samepage_hardmatch_bartmask_salientmask
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_bartmask_salientmask seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapas_data0_bart_samepage_hardmatch_bartmask_salientmask_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_bartmask_salientmask/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_salientmask_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_salientmask seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_salientmask/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_mentioncontext
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_mentioncontext
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_mentioncontext seq2seq 6 5 null
    --gradient-accumulation-steps 4 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_mentioncontext_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_topk3_bartmask_mentioncontext/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_3merge_bart_mlm_contextmention_bartbase_debug
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_mlm_contextmention_bartbase_debug seq2seq 24 10 null
    --gradient-accumulation-steps 3 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_3merge_bart_mlm_contextmention_bartbase_debug_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_deprecate base
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_mlm_contextmention_bartbase_debug/pytorch_model_epoch09.bin 10

- name: bart_base_wtqqa_deprecate_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_deprecate base full
    /mnt/root/TaBERT/data/runs/bartbase_finetune 30:50

- name: wholetable_tapex_05m_bart_bartmask_salientmask
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_tapex_05m_bart_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_bartmask_salientmask seq2seq 6 5 null
    --gradient-accumulation-steps 4 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapex_05m_bart_bartmask_salientmask_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_bartmask_salientmask/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapex_05m_bart_qa
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapex_05m_bart_qa
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_qa seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: wholetable_tapex_05m_bart_qa_finetune
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_qa/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_tapex_05m_bart_qa_tapexbaseinit_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapex_05m_bart_qa
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_qa_tapexbaseinit seq2seq 6 5
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_tapex_05m_bart_qa_tapexbaseinit/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_3merge_tapex05m_bart_bartmask_salientmask_tapexbaseinit_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_tapex05m_bart_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_3merge_tapex05m_bart_bartmask_salientmask_tapexbaseinit seq2seq 6 5
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_tapex05m_bart_bartmask_salientmask_tapexbaseinit/pytorch_model_epoch04.bin 10:30:50

- name: wholetable_wtq_bart_samepage_hardmatch_bartmask_salientmask_and_finetune
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_wtq_bart_samepage_hardmatch_bartmask_salientmask
    /mnt/root/TaBERT/data/runs/wholetable_wtq_bart_samepage_hardmatch_bartmask_salientmask seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/wholetable_wtq_bart_samepage_hardmatch_bartmask_salientmask/pytorch_model_epoch09.bin 10:30:50
