description: clean text on TOTTO

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:

- name: cleantext
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_totto_bart_cleantext
    /mnt/root/TaBERT/data/runs/wholetable_totto_bart_cleantext seq2seq 6 10 null
    --gradient-accumulation-steps 4 --base-model-name /mnt/root/TaBERT/data/runs/bart_base

- name: cleantext_bartlarge
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_totto_bart_cleantext
    /mnt/root/TaBERT/data/runs/wholetable_totto_bart_cleantext_bartlarge seq2seq 2 10 null
    --gradient-accumulation-steps 12 --base-model-name facebook/bart-large
