description: pretrain

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_2command
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell seq2seq 24 5 null
    --gradient-accumulation-steps 3
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 3
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_2command_8gpu
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_8gpu
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_8gpu seq2seq 24 5 null
    --gradient-accumulation-steps 3
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_8gpu_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_8gpu/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 3
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_2command
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole seq2seq 24 5 null
    --gradient-accumulation-steps 3
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 3
