description: pretrain

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_2command
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell seq2seq 24 5 null
    --gradient-accumulation-steps 3
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 3

- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_2command
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm seq2seq 24 5 null
    --gradient-accumulation-steps 6
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 6
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_continue_finetune
  sku: G4
  command:
  - ./finetune.sh 4 wtqqa:wikisqlqa:turl_sa:turl_cf
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_whole_avg_cell_norm_continue/pytorch_model_epoch09.bin

- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_2command
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole seq2seq 24 5 null
    --gradient-accumulation-steps 3
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_mlm_contextmention
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_continue seq2seq 24 10
    '"/mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole/pytorch_model_epoch04.bin"'
    --gradient-accumulation-steps 3
- name: wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_continue_finetune
  sku: G4
  command:
  - ./finetune.sh 4 wtqqa:wikisqlqa:turl_sa:turl_cf
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_mlm_contextmention_dense_span_context_as_whole_continue/pytorch_model_epoch09.bin

- name: wtqqa_tapex
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_ep10 seq2seq 24 10 null
    --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_ep50
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_ep50 seq2seq 24 50 null
    --mode generate-test --output_file ep49.tsv

- name: wtqqa_tapex_linear
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_linear_ep10 seq2seq 24 10 null
    --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_linear_1024
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_linear_1024_ep10 seq2seq 12 10 null
    --base-model-name facebook/bart-base
    --mode generate-test --output_file ep09.tsv
- name: wtqqa_tapex_linear_1024_ep50
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_linear_1024_ep50 seq2seq 12 50 null
    --base-model-name facebook/bart-base
    --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_1024_ep50_test
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/bart_base_wtq_tapex_linear_1024_ep50 50

- name: wtqqa_tapex_large
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_ep10 seq2seq 12 10 null
    --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_large_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_ep10 08:07:06:05:04:03:02:01:00

- name: wtqqa_tapex_linear_large
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep10 seq2seq 12 10 null
    --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_linear_large_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep10 08:07:06:05:04:03:02:01:00

- name: wtqqa_tapex_linear_large_tapex
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_ep10 seq2seq 12 10
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --base-model-name facebook/bart-large --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_linear_large_tapex_ep50
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_ep50 seq2seq 12 50
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --base-model-name facebook/bart-large --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_large_tapex_ep50_test
  sku: G4
  command:
  - ./predict.sh 4 wtqqa_tapex_large
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_ep50 05:07:10:13:15:20:25:30:40
    --base-model-name facebook/bart-large

- name: wtqqa_tapex_linear_1024_large_tapex_ep10
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_1024_ep10 seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_large_tapex_ep10
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_ep10 seq2seq 6 10
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --gradient-accumulation-steps 4
    --base-model-name facebook/bart-large --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_linear_1024_base_tapex_ep10
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/tapex_base_wtq_tapex_linear_1024_ep10 seq2seq 8 10
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 3
    --base-model-name facebook/bart-base --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_linear_1024_num128_base_tapex
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 base full
    /mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin 10:30:50
- name: wtqqa_tapex_linear_1024_num128_base_tapex2
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_strict_128 base full
    /mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin 10:30:50

- name: wtqqa_tapex_linear_1024_num128_base_bart
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 base full
    /mnt/root/TaBERT/data/runs/bart_base/pytorch_model.bin 10:30:50
- name: wtqqa_tapex_linear_1024_num128_base_bart2
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_strict_128 base full
    /mnt/root/TaBERT/data/runs/bart_base/pytorch_model.bin 10:30:50

- name: wtqqa_tapex_linear_1024_base_tapex_ep50
  sku: G4
  command:
  - ./run_vanilla.sh 4
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/tapex_base_wtq_tapex_linear_1024_ep50 seq2seq 8 50
    '"/mnt/root/TaBERT/data/runs/tapex_base/pytorch_model.bin"'
    --gradient-accumulation-steps 3
    --base-model-name facebook/bart-base --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_1024_base_tapex_ep50_test
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa base full
    /mnt/root/TaBERT/data/runs/tapex_base_wtq_tapex_linear_1024_ep50 50

- name: wtqqa_tapex_linear_1024_large_tapex
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_1024_ep50 seq2seq 6 50
    '"/mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin"'
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_1024_large_tapex_test
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa large full
    /mnt/root/TaBERT/data/runs/tapex_large_wtq_tapex_linear_1024_ep50 50
- name: wtqqa_tapex_linear_1024_num128_large_tapex
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin 10:30:50
- name: wtqqa_tapex_linear_1024_num128_large_tapex2
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/tapex_large/pytorch_model.bin 100

- name: wtqqa_tapex_linear_1024_num128_large_bart
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/bart_large/pytorch_model.bin 10:30:50
- name: wtqqa_tapex_linear_1024_num128_large_bart2  # lr 1e-5
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/bart_large/pytorch_model.bin 50
- name: wtqqa_tapex_linear_1024_num128_large_bart3  # lr 5e-6
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/bart_large/pytorch_model.bin 50
- name: wtqqa_tapex_linear_1024_num128_large_bart4
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/bart_large/pytorch_model.bin 200:500
- name: wtqqa_tapex_linear_1024_num128_large_bart5  # lr 2e-6
  sku: G8
  command:
  - ./finetune_predict.sh wtqqa_128 large full
    /mnt/root/TaBERT/data/runs/bart_large/pytorch_model.bin 200:500

- name: wtqqa_tapex_linear_large_bartxsum
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bartxsum_large_wtq_tapex_linear_ep10 seq2seq 12 10 null
    --base-model-name facebook/bart-large-xsum --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_linear_large_bartxsum_test
  sku: G4
  command:
  - ./predict.sh 4 wtqqa_tapex_large
    /mnt/root/TaBERT/data/runs/bartxsum_large_wtq_tapex_linear_ep10 08:00:07:01:06:02:05:03:04
    --base-model-name facebook/bart-large-xsum

- name: wtqqa_tapex_linear_large_bartcnn
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bartcnn_large_wtq_tapex_linear_ep10 seq2seq 12 10 null
    --base-model-name facebook/bart-large-cnn --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_linear_large_bs256
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 16
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep10_bs256 seq2seq 16 10 null
    --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_linear_large_bs256_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep10_bs256 08:07:06:05:04:03:02:01:00

- name: wtqqa_tapex_large_ep50
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_ep50 seq2seq 12 50 null
    --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_large_ep50_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_ep50 05:07:10:13:15:20:25:30:40

- name: wtqqa_tapex_1024_large_ep10
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_1024
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_1024_ep10 seq2seq 6 10 null
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep9.tsv
- name: wtqqa_tapex_1024_large_ep10_test
  sku: G4
  command:
  - ./predict.sh 4 wtqqa_tapex_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_1024_ep10 09:08:07:06:05:04:03:02:01:00
    --base-model-name facebook/bart-large

- name: wtqqa_tapex_1024_large
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_allrow_1024
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_1024_ep50 seq2seq 6 50 null
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_1024_large_test
  sku: G4
  command:
  - ./predict.sh 4 wtqqa_tapex_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_1024_ep50 05:07:10:13:15:20:25:30:40
    --base-model-name facebook/bart-large

- name: wtqqa_tapex_linear_large_ep50
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep50 seq2seq 12 50 null
    --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_large_ep50_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep50 08:07:06:05:04:03:02:01:00

- name: wtqqa_tapex_linear_1024_large_ep10
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_1024_ep10 seq2seq 6 10 null
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep9.tsv

- name: wtqqa_tapex_linear_1024_large
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_1024
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_1024_ep50 seq2seq 6 50 null
    --gradient-accumulation-steps 2
    --base-model-name facebook/bart-large --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_1024_large_test
  sku: G4
  command:
  - ./predict.sh 4 wtqqa_tapex_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_1024_ep50 05:07:10:13:15:20:25:30:40
    --base-model-name facebook/bart-large

- name: wtqqa_tapex_linear_large_ep50_bs256
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 16
    /mnt/root/TaBERT/data/train_data/wtq_qa_tapex_bart_large
    /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep50_bs256 seq2seq 16 50 null
    --mode generate-test --output_file ep49.tsv
- name: wtqqa_tapex_linear_large_ep50_bs256_test
  sku: G8
  command:
  - ./predict.sh 8 wtqqa_tapex_large /mnt/root/TaBERT/data/runs/bart_large_wtq_tapex_linear_ep50_bs256 05:07:10:13:15:20:25:30:40
