description: data2text pretrain

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:

- name: 3merge_data2text
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_3merge_bart_data2text
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_data2text seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_data2text/pytorch_model_epoch09.bin 30
- name: 3merge_data2text_finetune
  sku: G8
  command:
  - ./finetune_predict.sh totto_1_100 base full
    /mnt/root/TaBERT/data/runs/wholetable_3merge_bart_data2text/pytorch_model_epoch09.bin 50

- name: totto_originalsentence_data2text
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_totto_originalsentence_bart_data2text
    /mnt/root/TaBERT/data/runs/wholetable_totto_originalsentence_bart_data2text seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_totto_originalsentence_bart_data2text/pytorch_model_epoch09.bin 30

- name: tapas_data0_samepage_hardmatch_data2text
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text/pytorch_model_epoch04.bin 30
- name: tapas_data0_samepage_hardmatch_data2text_finetune
  sku: G8
  command:
  - ./finetune_predict.sh totto_1_100 base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text/pytorch_model_epoch04.bin 50
- name: tapas_data0_samepage_hardmatch_data2text_ep10
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_ep10 seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_ep10/pytorch_model_epoch09.bin 30

- name: tapas_data0_samepage_hardmatch_data2text_cleaned
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_cleaned
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_cleaned seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto_1_100 base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_cleaned/pytorch_model_epoch04.bin 30
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_data2text_cleaned/pytorch_model_epoch04.bin 30

- name: tapas_data0_samepage_hardmatch_morethan3_data2text
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_samepage_hardmatch_morethan3_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_morethan3_data2text seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_samepage_hardmatch_morethan3_data2text/pytorch_model_epoch04.bin 30

- name: tapas_data0_raw_data2text
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_raw_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_raw_data2text seq2seq 6 5 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_raw_data2text/pytorch_model_epoch04.bin 30
- name: tapas_data0_raw_data2text_finetune
  sku: G8
  command:
  - ./finetune_predict.sh totto_1_100 base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_raw_data2text/pytorch_model_epoch04.bin 50
- name: tapas_data0_raw_data2text_ep10
  sku: G8
  command:
  - ./run_vanilla.sh 8
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_data0_bart_raw_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_raw_data2text_ep10 seq2seq 6 10 null
    --gradient-accumulation-steps 12 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_data0_bart_raw_data2text_ep10/pytorch_model_epoch09.bin 30

- name: tapas_raw_data2text
  sku: G8
  sku_count: 3
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh 24
    /mnt/root/TaBERT/data/train_data/wholetable_tapas_bart_raw_data2text
    /mnt/root/TaBERT/data/runs/wholetable_tapas_bart_raw_data2text seq2seq 6 5 null
    --gradient-accumulation-steps 4 --base-model-name /mnt/root/TaBERT/data/runs/bart_base
- name: tapas_raw_data2text_finetune
  sku: G8
  command:
  - ./finetune_predict.sh totto base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_bart_raw_data2text/pytorch_model_epoch04.bin 30
- name: tapas_raw_data2text_finetune2
  sku: G8
  command:
  - ./finetune_predict.sh totto_1_100 base full
    /mnt/root/TaBERT/data/runs/wholetable_tapas_bart_raw_data2text/pytorch_model_epoch04.bin 50
