description: pretrain

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: tabert_electra_contrast_concat_quarter_fast
  sku: G8
  sku_count: 4
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_electra_quarter
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_contrastive_concat_quarter_ep5_fast 32 5
- name: tabert_2row
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_2row
    /mnt/root/TaBERT/data/runs/vanilla_tabert_2row_ep5 32 5
- name: tabert_electra_2row
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_electra_2row
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_2row_ep5 32 5
- name: tabert_totto_maskvalue
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_ep5 32 5
- name: tabert_totto_maskvalue_samplevalue
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue_samplevalue
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_ep5 32 5
- name: tabert_totto_maskvalue_samplevalue_maskusedcolumn
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue_samplevalue_maskusedcolumn
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_maskusedcolumn_ep5 32 5
- name: tabert_totto_maskseparate
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep10 32 10
- name: tabert_totto_maskwhole
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskwhole
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskwhole_ep10 32 10
- name: tabert_totto_maskseparate_nsp
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_nsp_ep10 5 10
- name: tabert_totto_maskseparate_contrastive_concat
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_contrastive_concat_ep10 5 10
