description: pretrain

environment:
  image: jzbjyb/my-repo:latest

target:
  service: amlk8s
  name: itp-scus-v100
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: tabert_electra_contrast_concat_quarter_fast
  sku: G8
  sku_count: 4
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_electra_quarter
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_contrastive_concat_quarter_ep5_fast contrast-concat_mlm 32 5
- name: tabert_2row
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_2row
    /mnt/root/TaBERT/data/runs/vanilla_tabert_2row_ep5 mlm 32 5
- name: tabert_electra_2row
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_electra_2row
    /mnt/root/TaBERT/data/runs/vanilla_tabert_electra_2row_ep5 mlm 32 5
- name: tabert_totto_maskvalue
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_ep5 mlm 32 5
- name: tabert_totto_maskvalue_samplevalue
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue_samplevalue
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_ep5 mlm 32 5
- name: tabert_totto_maskvalue_samplevalue_maskusedcolumn
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskvalue_samplevalue_maskusedcolumn
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskvalue_samplevalue_maskusedcolumn_ep5 mlm 32 5
- name: tabert_totto_maskseparate
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep10 mlm 32 10
- name: tabert_totto_maskseparate_ep20
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_ep20 mlm 32 20
- name: tabert_totto_maskwhole
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskwhole
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskwhole_ep10 mlm 32 10
- name: tabert_totto_maskseparate_nsp
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_nsp_ep10 mlm 5 10
- name: tabert_totto_maskseparate_nsp_ep20
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_nsp_ep20 mlm 5 20
- name: tabert_totto_maskseparate_contrastive_concat
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_contrastive_concat_ep10 mlm 5 10
- name: tabert_totto_maskseparate_bart_all
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_bart_all_ep20 table2text_text2table_mlm 10 20
- name: tabert_totto_maskseparate_bart_mlm
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_bart_mlm_ep20 mlm 24 20
- name: tabert_totto_maskseparate_bart_table2texttext2table
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_bart_table2texttext2table_ep20 table2text_text2table 10 20
- name: tabert_totto_maskseparate_bart_table2textmlm
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_bart_table2textmlm_ep20 table2text_mlm 10 20
- name: tabert_totto_maskseparate_bart_text2tablemlm
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_totto_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_maskseparate_bart_text2tablemlm_ep20 text2table_mlm 10 20
- name: tabert_totto_hardneg_maskseparate_binary
  sku: G8
  sku_count: 6
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_hardneg_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_hardneg_maskseparate_binary_ep20 binary_mlm 32 20
- name: tabert_totto_randneg_maskseparate_binary
  sku: G8
  sku_count: 6
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_totto_randneg_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_totto_randneg_maskseparate_binary_ep20 binary_mlm 32 20

- name: tabert_onlytable
  sku: G8
  sku_count: 6
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert
    /mnt/root/TaBERT/data/runs/vanilla_tabert_onlytable_ep5 mlm 32 5
- name: tabert_bart_onlytable_maskseparate
  sku: G8
  sku_count: 6
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_bart_onlytable_maskseparate_ep5 mlm 24 5

# seq2seq pretrain
- name: tabert_bart_3merge_seq2seq
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_3merge_seq2seq_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_bart_3merge_seq2seq_ep5 seq2seq 24 5
- name: tabert_bart_3merge_seq2seq_nomlm
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_3merge_seq2seq_nomlm_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_bart_3merge_seq2seq_nomlm_ep5 seq2seq 24 5

# seq2seq pretrain with init from onlytable
- name: tabert_bart_3merge_seq2seq_onlytable
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_3merge_seq2seq_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_bart_3merge_seq2seq_onlytable_ep5 seq2seq 24 5
- name: tabert_bart_3merge_seq2seq_nomlm_onlytable
  sku: G8
  sku_count: 2
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/vanilla_tabert_bart_3merge_seq2seq_nomlm_maskseparate
    /mnt/root/TaBERT/data/runs/vanilla_tabert_bart_3merge_seq2seq_nomlm_onlytable_ep5 seq2seq 24 5

# wikisql qa
- name: bart_wikisql_qa
  sku: G8
  sku_count: 1
  aml_mpirun:
    process_count_per_node: 8
    communicator: "OpenMpi"
  command:
  - ./run_vanilla.sh
    /mnt/root/TaBERT/data/train_data/wikisql_qa_firstansrow
    /mnt/root/TaBERT/data/runs/bart_wikisql_qa seq2seq 24 10
