description: sql2nl

environment:
  image: jzbjyb/my-repo:latest

#target:
#  service: amlk8s
#  name: itp-scus-v100
#  vc: AlexTScience
target:
  service: aml
  name: V10032G
  vc: AlexTScience

storage:
  data:
    storage_account_name: tsinterns
    container_name: t-zhjiang
    mount_dir: /mnt/root

code:
  local_dir: $CONFIG_DIR

jobs:
- name: wtq_sqltable2nl_denormalized_num16_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num16
    wtq_sqltable2nl_denormalized_num16_bartlarge
    null
    2 1 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num16_bartlarge
    wtq_sqltable2nl_denormalized_num16_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num16/nl.txt

- name: wtq_sqltable2nl_denormalized_num32_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num32
    wtq_sqltable2nl_denormalized_num32_bartlarge
    null
    2 2 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num32_bartlarge
    wtq_sqltable2nl_denormalized_num32_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num32/nl.txt

- name: wtq_sqltable2nl_denormalized_num64_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num64
    wtq_sqltable2nl_denormalized_num64_bartlarge
    null
    2 4 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num64_bartlarge
    wtq_sqltable2nl_denormalized_num64_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num64/nl.txt

- name: wtq_sqltable2nl_denormalized_num128_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num128
    wtq_sqltable2nl_denormalized_num128_bartlarge
    null
    2 8 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num128_bartlarge
    wtq_sqltable2nl_denormalized_num128_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num128/nl.txt

- name: wtq_sqltable2nl_denormalized_num256_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num256
    wtq_sqltable2nl_denormalized_num256_bartlarge
    null
    2 16 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num256_bartlarge
    wtq_sqltable2nl_denormalized_num256_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num256/nl.txt

- name: wtq_sqltable2nl_denormalized_num512_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num512
    wtq_sqltable2nl_denormalized_num512_bartlarge
    null
    2 16 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num512_bartlarge
    wtq_sqltable2nl_denormalized_num512_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num512/nl.txt

- name: wtq_sqltable2nl_denormalized_num1024_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized_num1024
    wtq_sqltable2nl_denormalized_num1024_bartlarge
    null
    2 16 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_num1024_bartlarge
    wtq_sqltable2nl_denormalized_num1024_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized_num1024/nl.txt

- name: wtq_sqltable2nl_denormalized_bartlarge
  sku: G8
  command:
  - ./run_model.sh 8 large
    wtq_sqltable2nl_denormalized
    wtq_sqltable2nl_denormalized_bartlarge
    null
    2 16 50
  - ./run_model.sh 8 large
    tapex_05m_sqltable2nl
    wtq_sqltable2nl_denormalized_bartlarge
    wtq_sqltable2nl_denormalized_bartlarge/pytorch_model_epoch49.bin
    8 1 1
    --only_test
    --mode generate-train
    --output_file /mnt/root/TaBERT/data/train_data/tapex_05m_sqltable2nl/wtq_sqltable2nl_denormalized/nl.txt
